# Generated by Django 3.0.2 on 2020-01-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('state', models.CharField(choices=[(1, 'ACTIVE'), (2, 'ARCHIVE')], max_length=7)),
                ('owner', models.IntegerField(null=True)),
            ],
        ),
    ]
