# Generated by Django 3.0.2 on 2020-01-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectorApp', '0002_auto_20200121_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
